language: python
python:
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -r requirements.txt
  - pip install flake8
before_script:
  - flake8 .
script:
  - pytest
deploy:
  provider: pypi
  user: "UpGado"
  password:
    secure: bDLod+Mf1eV5e1uE39qtrjR3OCp5NlsnXa+GdhtbRi6tgkgb63foVAB/z0F2kKxzTHWgT6Zl+IIH9m4bZPvpblITKeLke16gG6s1qoXPkEIYInBTOYhJxe9noHvox6mD9dcffX3MZv5O0UOYnujOm0Mb7iIASJzInL8o54ALF0jar8/MLcJPVE+xGYIIgperUhgZPHcAEvpYUZTGsJ4EAHiTnPaq4cFw7FGf7KJJXKZ1aiuI0nu1xJFSvVwrCKd0S96y3+2+xe/DocHap7ZX8fau5CwtQ4CSbXew7dv+U2mYv3hdxxxZh0if10IgIn2iNrw6Tomps98XLuzm5aPDX7eKBeSJdwrZ6rDh/SUODOr34yGSZoXE3eUThqRaSsy+JGwUYleG4HlxiR/KhdD+H1avrnOMQavP9FY3g93BGmnvtBPfcHg6gn46gxV1Z9zOvSRjlDn0erQ/UEZtCiy6to8OoRdXudxYffhfNcv9MlWyR+jPB9wqmJbGdM3Ao0WHwLFYFUNo1Z1/38rnGQwtdErwTU41GsnEYhgKD1Z38NRKnXnseYtGDvy66dugI2ukkxc5LK1V8Hu6r6WHeObQdUlMBAGZ4GOli0YAh5zi8RXcW9FR8xVeeYOD8/p5T4RQh5QMBMsdmkalnPzYf783oPS0YE/Pp0yY1tG9UxjsND0=
  on:
    tags: true
    python: "3.7"
  distributions: "sdist bdist_wheel"
